name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Cross building
        run: |
          oslist="linux darwin windows"
          # Support all archs
          archlist="386 amd64 arm arm64"
          for os in $oslist; do
            for arch in $archlist; do
              CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -o .build/http2tcp-$os-$arch
            done
          done
      - name: Generate body
        run: |
          echo '**Build At**:

          * `'"$(date)"'`
          * `'"$(TZ=Asia/Shanghai date)"'`

          **sha256sum**:

          ```-
          '"$(cd .build && sha256sum *)"'
          ```
          ' > body.md
      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
          name: main
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          artifacts: .build/*
          commit: main
          tag: release-main-latest
          bodyFile: body.md
