name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Cross building
        run: |
          oslist="linux darwin windows"
          # Support all archs
          archlist="amd64 arm64"
          for os in $oslist; do
            for arch in $archlist; do
              CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -o .build/http2tcp-$os-$arch
            done
          done

      - name: Set branch environment variable
        run: |
          currentBranch=$(git branch --show-current)
          now_date=$(date "+%Y-%m-%d_%H-%M-%S")
          
          echo "project_branch=${currentBranch}-${now_date}" >> ${GITHUB_ENV}

      - name: mv and tar build file
        run: |
          mv .build/http2tcp-windows-amd64 .build/http2tcp-windows-amd64.exe
          mv .build/http2tcp-windows-arm64 .build/http2tcp-windows-arm64.exe
          tar -czvf build-all.tar.gz .build/*
          mv build-all.tar.gz .build/

      - name: Generate body
        run: |
          echo '**Build At**:

          * `'"$(TZ=Asia/Shanghai date)"'`

          **sha256sum**:

          ```-
          '"$(cd .build && sha256sum *)"'
          ```
          ' > body.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          artifacts: .build/*
          tag: ${{ env.project_branch }}
          bodyFile: body.md
