name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Cross building
        run: |
          go tool dist list | while IFS= read -r line
          do
            IFS='/' read -ra OS_ARCH <<< "$line"
            CGO_ENABLED=0 GOOS=${OS_ARCH[0]} GOARCH=${OS_ARCH[1]} go build -o .build/http2tcp-$os-$arch
          done
      - name: Generate body
        run: |
          echo '**Build At**:

          * `'"$(TZ=Asia/Shanghai date)"'`

          **sha256sum**:

          ```-
          '"$(cd .build && sha256sum *)"'
          ```
          ' > body.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.sha }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          artifacts: .build/*
          commit: ${{ github.sha }}
          tag: release-latest
          bodyFile: body.md
